name: Run tests
description: "Run the tests"
runs:
  using: 'composite'
  steps:
    - name: Install Python Dependencies
      shell: bash
      run: uv sync --frozen --all-groups --all-extras

    - name: Run tests
      shell: bash
      run: |
        uv run --no-sync pytest -v --cov=. --cov-report=html